import { lazy, type ComponentType } from "react"
import type { LucideIcon } from "lucide-react"
import {
  Sparkles,
  Puzzle,
  ToggleLeft,
  MousePointerClick,
  GitBranch,
  ListOrdered,
  FormInput,
  Code2,
  Blocks,
  Waves,
  Crosshair,
  Receipt,
  Fingerprint,
  Wrench,
  ListChecks,
  Globe,
  Signpost,
  Route,
  Radio,
  Boxes,
  Gauge,
  PackageOpen,
  ShieldAlert,
} from "lucide-react"

export type Section = "fundamentals" | "hooks" | "real-apps" | "state-management" | "advanced"

export const SECTIONS: Record<Section, string> = {
  fundamentals: "Fundamentals",
  hooks: "Hooks",
  "real-apps": "Real Applications",
  "state-management": "State Management",
  advanced: "Advanced React",
}

export interface Lesson {
  slug: string
  order: number
  section: Section
  title: string
  shortTitle: string
  description: string
  icon: LucideIcon
  minutes: number
  component: ComponentType
}

export const lessons: Lesson[] = [
  {
    slug: "what-is-react",
    order: 1,
    section: "fundamentals",
    title: "What is React?",
    shortTitle: "What is React?",
    description: "Understand what React is, why it exists, and how it thinks about UI.",
    icon: Sparkles,
    minutes: 6,
    component: lazy(() => import("@/lessons/01-what-is-react")),
  },
  {
    slug: "jsx-basics",
    order: 2,
    section: "fundamentals",
    title: "JSX Basics",
    shortTitle: "JSX Basics",
    description: "Write UI with JSX — HTML-like syntax that compiles to JavaScript.",
    icon: Code2,
    minutes: 8,
    component: lazy(() => import("@/lessons/02-jsx-basics")),
  },
  {
    slug: "components-props",
    order: 3,
    section: "fundamentals",
    title: "Components & Props",
    shortTitle: "Components & Props",
    description: "Break UI into reusable components and pass data to them with props.",
    icon: Puzzle,
    minutes: 10,
    component: lazy(() => import("@/lessons/03-components-props")),
  },
  {
    slug: "state",
    order: 4,
    section: "fundamentals",
    title: "State with useState",
    shortTitle: "State (useState)",
    description: "Give components memory so the UI can change over time.",
    icon: ToggleLeft,
    minutes: 10,
    component: lazy(() => import("@/lessons/04-state")),
  },
  {
    slug: "events",
    order: 5,
    section: "fundamentals",
    title: "Handling Events",
    shortTitle: "Handling Events",
    description: "Respond to clicks, typing, and other user interaction.",
    icon: MousePointerClick,
    minutes: 7,
    component: lazy(() => import("@/lessons/05-events")),
  },
  {
    slug: "conditional-rendering",
    order: 6,
    section: "fundamentals",
    title: "Conditional Rendering",
    shortTitle: "Conditional Rendering",
    description: "Show or hide UI depending on state, with clean patterns.",
    icon: GitBranch,
    minutes: 8,
    component: lazy(() => import("@/lessons/06-conditional-rendering")),
  },
  {
    slug: "lists-and-keys",
    order: 7,
    section: "fundamentals",
    title: "Rendering Lists & Keys",
    shortTitle: "Lists & Keys",
    description: "Turn arrays of data into repeated UI, the right way.",
    icon: ListOrdered,
    minutes: 8,
    component: lazy(() => import("@/lessons/07-lists-and-keys")),
  },
  {
    slug: "forms",
    order: 8,
    section: "fundamentals",
    title: "Forms & Controlled Inputs",
    shortTitle: "Forms",
    description: "Capture user input with controlled form elements.",
    icon: FormInput,
    minutes: 10,
    component: lazy(() => import("@/lessons/08-forms")),
  },
  {
    slug: "hooks-overview",
    order: 9,
    section: "hooks",
    title: "Hooks: The Big Picture",
    shortTitle: "Hooks Overview",
    description: "What Hooks are, why they exist, and a map of the ones worth knowing.",
    icon: Blocks,
    minutes: 6,
    component: lazy(() => import("@/lessons/09-hooks-overview")),
  },
  {
    slug: "use-effect",
    order: 10,
    section: "hooks",
    title: "useEffect",
    shortTitle: "useEffect",
    description: "Sync a component with something outside React, like a timer or an API.",
    icon: Waves,
    minutes: 12,
    component: lazy(() => import("@/lessons/10-use-effect")),
  },
  {
    slug: "use-ref",
    order: 11,
    section: "hooks",
    title: "useRef",
    shortTitle: "useRef",
    description: "Reach into the DOM directly, or remember a value without re-rendering.",
    icon: Crosshair,
    minutes: 9,
    component: lazy(() => import("@/lessons/11-use-ref")),
  },
  {
    slug: "use-memo",
    order: 12,
    section: "hooks",
    title: "useMemo",
    shortTitle: "useMemo",
    description: "Skip re-running an expensive calculation when nothing it depends on changed.",
    icon: Receipt,
    minutes: 9,
    component: lazy(() => import("@/lessons/12-use-memo")),
  },
  {
    slug: "use-callback",
    order: 13,
    section: "hooks",
    title: "useCallback",
    shortTitle: "useCallback",
    description: "Keep a function's identity stable across renders.",
    icon: Fingerprint,
    minutes: 9,
    component: lazy(() => import("@/lessons/13-use-callback")),
  },
  {
    slug: "custom-hooks",
    order: 14,
    section: "hooks",
    title: "Custom Hooks",
    shortTitle: "Custom Hooks",
    description: "Extract and reuse stateful logic between components.",
    icon: Wrench,
    minutes: 10,
    component: lazy(() => import("@/lessons/14-custom-hooks")),
  },
  {
    slug: "rules-of-hooks",
    order: 15,
    section: "hooks",
    title: "The Rules of Hooks",
    shortTitle: "Rules of Hooks",
    description: "Why Hooks must be called the same way on every render.",
    icon: ListChecks,
    minutes: 8,
    component: lazy(() => import("@/lessons/15-rules-of-hooks")),
  },
  {
    slug: "fetching-data",
    order: 16,
    section: "real-apps",
    title: "Fetching Data",
    shortTitle: "Fetching Data",
    description: "Load data from an API and handle loading, success, and error states.",
    icon: Globe,
    minutes: 12,
    component: lazy(() => import("@/lessons/16-fetching-data")),
  },
  {
    slug: "react-router-basics",
    order: 17,
    section: "real-apps",
    title: "React Router Basics",
    shortTitle: "React Router",
    description: "Show different UI for different URLs, without full page reloads.",
    icon: Signpost,
    minutes: 10,
    component: lazy(() => import("@/lessons/17-react-router-basics")),
  },
  {
    slug: "route-parameters",
    order: 18,
    section: "real-apps",
    title: "Route Parameters",
    shortTitle: "Route Parameters",
    description: "Read dynamic segments from the URL and fetch data to match.",
    icon: Route,
    minutes: 10,
    component: lazy(() => import("@/lessons/18-route-parameters")),
  },
  {
    slug: "context-api",
    order: 19,
    section: "state-management",
    title: "The Context API",
    shortTitle: "Context API",
    description: "Share a value with an entire subtree, without passing it through every level.",
    icon: Radio,
    minutes: 12,
    component: lazy(() => import("@/lessons/19-context-api")),
  },
  {
    slug: "redux-zustand",
    order: 20,
    section: "state-management",
    title: "Redux & Zustand",
    shortTitle: "Redux & Zustand",
    description: "The store-and-actions pattern for state too big or too shared for Context.",
    icon: Boxes,
    minutes: 14,
    component: lazy(() => import("@/lessons/20-redux-zustand")),
  },
  {
    slug: "rerenders-and-memo",
    order: 21,
    section: "advanced",
    title: "Re-renders & React.memo",
    shortTitle: "Re-renders & memo",
    description: "Why a child re-renders when its parent does, and how to stop it.",
    icon: Gauge,
    minutes: 11,
    component: lazy(() => import("@/lessons/21-rerenders-and-memo")),
  },
  {
    slug: "code-splitting",
    order: 22,
    section: "advanced",
    title: "Code Splitting with lazy & Suspense",
    shortTitle: "Code Splitting",
    description: "Load only the code a screen actually needs, exactly when it needs it.",
    icon: PackageOpen,
    minutes: 11,
    component: lazy(() => import("@/lessons/22-code-splitting")),
  },
  {
    slug: "error-boundaries",
    order: 23,
    section: "advanced",
    title: "Error Boundaries",
    shortTitle: "Error Boundaries",
    description: "Contain a crash to one part of the UI instead of a blank white screen.",
    icon: ShieldAlert,
    minutes: 10,
    component: lazy(() => import("@/lessons/23-error-boundaries")),
  },
]

export function getLessonBySlug(slug: string | undefined) {
  return lessons.find((lesson) => lesson.slug === slug)
}

export function getAdjacentLessons(slug: string) {
  const index = lessons.findIndex((lesson) => lesson.slug === slug)
  return {
    previous: index > 0 ? lessons[index - 1] : undefined,
    next: index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : undefined,
  }
}

export function getLessonsBySection() {
  return (Object.keys(SECTIONS) as Section[]).map((section) => ({
    section,
    label: SECTIONS[section],
    lessons: lessons.filter((lesson) => lesson.section === section),
  }))
}
